import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/Header'
import DevicesFoldIcon from "@mui/icons-material/DevicesFold";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className=" flex flex-row h-screen w-full">
          <Header />
          <div className=" bg-white flex-1 flex flex-col">
            <div className=" h-20 w-full border-b-2 sticky top-0 right-0 flex justify-between px-4 items-center">
              <DevicesFoldIcon className=" fill-blue-700 h-8 w-8" />
              <div className=" h-full flex justify-center items-center gap-2">
                <div className=" sm:h-12 sm:w-12 h-8 w-8 rounded-full bg-blue-500 flex justify-center items-center text-white font-medium sm:text-[24px] text-lg">
                  R
                </div>
                <div className=" flex flex-col justify-center font-medium items-start sm:text-[14px] text-sm leading-4">
                  <h1 className=" text-slate-700 ">
                    Rocky Karmakar
                  </h1>
                  <h2 className=" text-slate-500 font-normal sm:text-[12px] text-[10px]">
                    rocky.karmakar@cloudcraftz.io
                  </h2>
                </div>
              </div>
            </div>
            <div className=" flex-1 ">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
